/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"
#include "validate.h"
#include <stdlib.h>
#include <string.h>

void addUser(client_message *argp) {
   char* delimiter = "####";
   FILE *fp = fopen("./user.db","a+");
   if(fp != NULL) {
       char data[517]  = "";
       strcpy(data,argp->current_user.name);
       strcat(data,delimiter);
       strcat(data,argp->current_user.pass);
       strcat(data,"\n");
       fputs(data,fp);
       fclose(fp);
   }
}

server_message *
register_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;
	if(!isRegisteredUsername(argp))
	{
		addUser(argp);
		result.opcode = 00;
	} else result.opcode = 01;
	// printf("%s\n",argp->current_user.name );
	return &result;
}

server_message *
login_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;
  if(isValidUser(argp)) {
    result.opcode = 10;
  } else result.opcode = 11;
  return &result;
}

server_message *
logout_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
join_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
spin_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;
	result.opcode = rand()%15;
	return &result;
}

server_message *
open_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
guess_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
guess_all_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
surender_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
function1_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
function2_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
function3_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}
