/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"
#include "print.h"
#include "validate.h"
#define AUTHENTICATED 1

struct Session{
    struct User user;
    int sessStatus;// NOT IDENTIFIED USER, NOT AUTHENTICATED…
    struct sockaddr_in cliaddr;
};
struct Joiner{
    struct User user;
    int score;
    int in_game; // Check User still play in game ?
    char messageAction[200];
};
struct Game{
    int status; //0: game kết thúc, 1: còn game
    struct Joiner joiners[3];
    char question[100]; ///
    char answerAtMoment[100]; // “****ac***c”
};

void
wheel_prog_1(char *host)
{
	CLIENT *clnt;
	server_message  *result_1;
	client_message  register_1_arg;
	server_message  *result_2;
	client_message  login_1_arg;
	server_message  *result_3;
	client_message  logout_1_arg;
	server_message  *result_4;
	client_message  join_1_arg;
	server_message  *result_5;
	client_message  spin_1_arg;
	server_message  *result_6;
	client_message  open_1_arg;
	server_message  *result_7;
	client_message  guess_1_arg;
	server_message  *result_8;
	client_message  guess_all_1_arg;
	server_message  *result_9;
	client_message  surender_1_arg;
	server_message  *result_10;
	client_message  function1_1_arg;
	server_message  *result_11;
	client_message  function2_1_arg;
	server_message  *result_12;
	client_message  function3_1_arg;
  char choice;
  struct Session session;

#ifndef	DEBUG
	clnt = clnt_create (host, WHEEL_PROG, V1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

  welcome();
  menu_login();
  scanf("%c%*c",&choice);
  choice = validate_choice(&choice,'1','2');
  switch (choice) {
    case '1':
      strcpy(register_1_arg.command,"REGISTER");
      do {
        printf("Enter the username: ");
  		  scanf("%s%*c", register_1_arg.current_user.name);
  		  printf("Enter the password: ");
  		  scanf("%s%*c", register_1_arg.current_user.pass);

        result_1 = register_1(&register_1_arg, clnt);

        if (result_1 == (server_message *) NULL) {
          clnt_perror (clnt, "call failed"); break;
        }
        if (result_1->opcode == 0) {
          printf("Register successful!\n");
          session.user = register_1_arg.current_user;
          session.sessStatus = AUTHENTICATED;
        }
        else if (result_1->opcode == 1){
          printf("Your username is existed. Please register with another name.\n");
        }
      } while (result_1->opcode == 1);
      break;
    case '2':
      strcpy(login_1_arg.command,"LOGIN");
      do {
        printf("Enter the username: ");
        scanf("%s%*c", login_1_arg.current_user.name);
        printf("Enter the password: ");
        scanf("%s%*c", login_1_arg.current_user.pass);

        result_2 = login_1(&login_1_arg, clnt);

        if (result_2 == (server_message *) NULL) {
          clnt_perror (clnt, "call failed"); break;
        }
        if (result_2->opcode == 10) {
            printf("Login successful!\n");
            session.user = register_1_arg.current_user;
            session.sessStatus = AUTHENTICATED;
        }
        else if (result_2->opcode == 11){
          printf("Your username and password not match.\n");
        }
      } while (result_2->opcode == 11);
      break;
    default: break;
  }
  if (session.sessStatus == AUTHENTICATED) {
    printf("Press Enter to spin ");
    scanf("%c",&choice);
  	if (choice == '\n') {
  		strcpy(spin_1_arg.command,"SPIN");
  		result_5 = spin_1(&spin_1_arg, clnt);
  		if (result_5 == (server_message *) NULL) {
  			clnt_perror (clnt, "call failed");
  		} else print_spin_result(result_5->opcode);
  	}
  } else printf("You have not login.\n");

	result_3 = logout_1(&logout_1_arg, clnt);
	if (result_3 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = join_1(&join_1_arg, clnt);
	if (result_4 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_6 = open_1(&open_1_arg, clnt);
	if (result_6 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = guess_1(&guess_1_arg, clnt);
	if (result_7 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = guess_all_1(&guess_all_1_arg, clnt);
	if (result_8 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = surender_1(&surender_1_arg, clnt);
	if (result_9 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = function1_1(&function1_1_arg, clnt);
	if (result_10 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = function2_1(&function2_1_arg, clnt);
	if (result_11 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = function3_1(&function3_1_arg, clnt);
	if (result_12 == (server_message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	wheel_prog_1 (host);
exit (0);
}
