/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"

server_message *
register_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
login_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
logout_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
join_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
spin_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;
	result.opcode = rand()%15;
	return &result;
}

server_message *
open_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
guess_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
guess_all_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
surender_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
function1_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
function2_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}

server_message *
function3_1_svc(client_message *argp, struct svc_req *rqstp)
{
	static server_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}
