/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "main.h"

bool_t
xdr_User (XDR *xdrs, User *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pass, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->accStatus))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client_message (XDR *xdrs, client_message *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->command, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->parameter, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_User (xdrs, &objp->current_user))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Joiner (XDR *xdrs, Joiner *objp)
{
	register int32_t *buf;

	 if (!xdr_User (xdrs, &objp->user))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->score))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->in_game))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Quiz (XDR *xdrs, Quiz *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->question, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->answer, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_game (XDR *xdrs, game *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->joiners, 3,
		sizeof (Joiner), (xdrproc_t) xdr_Joiner))
		 return FALSE;
	 if (!xdr_Quiz (xdrs, &objp->quiz))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->answerAtMoment, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_server_message (XDR *xdrs, server_message *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->opcode))
		 return FALSE;
	 if (!xdr_game (xdrs, &objp->current_game))
		 return FALSE;
	return TRUE;
}
