/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPIN_H_RPCGEN
#define _SPIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SPINPROG 0x20000098
#define SPIN_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SPIN 1
extern  int * spin_1(char **, CLIENT *);
extern  int * spin_1_svc(char **, struct svc_req *);
extern int spinprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SPIN 1
extern  int * spin_1();
extern  int * spin_1_svc();
extern int spinprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SPIN_H_RPCGEN */
