/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "spin.h"
#include <time.h>
#include <stdlib.h>

int *
spin_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;
	srand(time(NULL));

	if (strcmp(*argp,"SPIN")==0) {
		result = rand()%15;
		printf("%d\n",result );
	}
	else {
		result = -1;
	}
	return &result;
}
